name: Generate ARM templates docs
on:
  push:
    branches: [ main ]
jobs:
  arm_docs:
    name: Generate ARM template docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate ARM markdowns
      run: |
        Install-Module -Name 'PSDocs.Azure' -Repository PSGallery -force;
        $VerbosePreference = 'Continue';
        Get-AzDocTemplateFile | ForEach-Object {
          write-host $_.TemplateFile;
          $temp = $_.TemplateFile |ConvertFrom-Json;
          $temp |fl;
          $template = Get-Item -Path $_.TemplateFile;
          $templateName = $template.Directory.Parent.Name;
          $version = $template.Directory.Name;
          $docName = "$($templateName)_$version";
          write-host $docName;
          # Generate markdown
          Invoke-PSDocument -Module PSDocs.Azure -OutputPath "out/docs" -InputObject $template.FullName -InstanceName $docName;
        };
        Get-ChildItem * -Recurse |foreach-object {$_.Fullname}
      shell: pwsh